### ISSUE TITLE
Goldeneye Multiplayer: Players 3&4 Not Rendering or Retroarch freezes

### ISSUE THREAD

**Issue by sweatypickle** [GLupeN64/GLupeN64#76] opened 2016-10-13 02:33 UTC
Windows build. Originally, the windows for Players 3&4 were grayed out and did not render properly but the game would work properly otherwise. ie: Players 3&4 could be controlled and you could see them working properly in the windows for Players 1&2. A build somewhere in September regressed this even further, as now just entering multiplayer causes RetroArch to freeze or crash completely.

![007 - goldeneye usa -161012-034606](https://cloud.githubusercontent.com/assets/12215615/19334694/c8900e4a-90cb-11e6-9048-7f53317c1692.png)

**Comment by loganmc10** [comment] 2016-10-13 14:37
I can reproduce the pictured issue (3&4 player not rendering) but I can't reproduce any crash. I've tried on Android, Linux, and Windows.

I'll look into the 3&4 player thing.

**Comment by loganmc10** [comment] 2016-10-13 14:41
I tested this with mupen64plus and it happens there as well, so this is an issue with GLideN64, I've opened an issue there:

https://github.com/gonetz/GLideN64/issues/1173

**Comment by loganmc10** [comment] 2016-11-05 01:28
@sweatypickle you can work around this issue for now by disabling "Framebuffer Emulation" in the core options

**Comment by loganmc10** [comment] 2016-11-22 03:12
I'm going to close this since it's definitely a GLideN64 issue and I've posted a work around, as well as filed an upstream issue

**Closed by loganmc10** 2016-11-22 03:12 UTC
Labels: upstream issue
